# Vetores e Arrays em NumPy

> Importando a biblioteca NumPy como np

In [5]:
import numpy as np

> Criando uma lista

In [6]:
minha_lista = [1,2,3]

#### Array Unidimensional (Vetor)

> Exibindo a lista criada

In [7]:
minha_lista

[1, 2, 3]

> Criando um array com a lista criada

In [8]:
np.array(minha_lista)

array([1, 2, 3])

#### Array Bidimensional (Matriz)

> Criando uma matriz

In [9]:
minha_matriz = [[1,2,3], [4,5,6], [7,8,9]]

> Criando uma array bidimensional com a matriz

In [10]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Utilizando metódos de np para criar/exibir Vetores

> Exibindo uma array de 0 a 10

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Exibindo uma array entre 0 e 10 com os valores de 2 em 2, pares.

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

> Exibindo uma array composta por zeros

In [14]:
np.zeros(3)

array([0., 0., 0.])

> Atribuindo uma array composta por zeros à arr

In [15]:
arr = np.zeros(3)

#### Manipulandos as Arrays com NumPy

> Atribuindo uma array bidimensional, 5x5, composta por zeros, à arr

In [19]:
arr = np.zeros((5,5))

In [20]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

> Exibindo uma array bidimensional, 7x32, composta apenas por um 

In [21]:
np.ones((7,32))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.

> Exibindo uma array, 4x4, que consiste em uma matriz identidade.

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

> Exibindo uma array de 5 números entre 0 e 10 proporcionais a 5.

In [57]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### Arrays com valores aleatórios utilizando numpy.random

> Exibindo uma array de 5 composta por números decimais aleatorios entre 0 e 1.

In [32]:
np.random.rand (5)

array([0.75780302, 0.13099044, 0.55868621, 0.84451192, 0.80210415])

> Exibindo uma array tridimensional, 5x4x3 composta por números decimais aleatorios entre 0 e 1

In [34]:
np.random.rand (5,4,3)

array([[[0.83710625, 0.68064183, 0.27102595],
        [0.74950765, 0.81126781, 0.816534  ],
        [0.3466197 , 0.13102391, 0.25121322],
        [0.24679427, 0.31683522, 0.05089185]],

       [[0.10370301, 0.74860106, 0.02008965],
        [0.19477348, 0.29492428, 0.54322829],
        [0.17923831, 0.76540832, 0.28477534],
        [0.12863596, 0.5312516 , 0.85968839]],

       [[0.08321286, 0.93204822, 0.46424097],
        [0.59812422, 0.6899965 , 0.42161448],
        [0.32786308, 0.04189639, 0.70665492],
        [0.22729208, 0.93509212, 0.34022471]],

       [[0.18398956, 0.74552718, 0.8220951 ],
        [0.49858316, 0.74380503, 0.18241632],
        [0.50201331, 0.57152238, 0.84809625],
        [0.99432338, 0.06028744, 0.99067317]],

       [[0.50522695, 0.33381342, 0.56714878],
        [0.60941969, 0.7647513 , 0.60594964],
        [0.60383952, 0.06480279, 0.62507284],
        [0.32003255, 0.4143027 , 0.15611292]]])

> Exibindo uma array composta por 4 números gaussianos aleatorios 

In [35]:
np.random.randn (4)

array([ 2.2852258 , -1.62036472, -0.32839055,  1.19275881])

> Exibindo uma array composta por 5 números inteiros aleatórios entre 0 e 100

In [37]:
np.random.randint (0, 100, 5)

array([12, 89, 69, 36, 53])

> Exibindo uma array composta por 5 números inteiros aleatórios entre 0 e 100, utilizando o metódo round

In [38]:
np.round(np.random.rand(5)*100, 0)

array([71., 89., 14., 94., 33.])

> Atribuindo uma array composta por 25 posições de números aleatórios entre 0 e 1 à arr e exibindo-o

In [39]:
arr = np.random.rand(25)

In [40]:
arr

array([0.68910005, 0.98061642, 0.8044563 , 0.19071096, 0.14393131,
       0.06482917, 0.537428  , 0.87073117, 0.84501176, 0.81203825,
       0.39533731, 0.14346841, 0.65920755, 0.98401088, 0.90914703,
       0.10233533, 0.88033573, 0.37520208, 0.44566714, 0.18751585,
       0.27021355, 0.48831245, 0.70425311, 0.01940983, 0.11725166])

> Utilizando reshape para transformar a arr de 25 posições em uma array bidimensional 5x5, mantendo os mesmos valores e respectivas posições.

#### Analisando Arrays (suas dimensões e valores)

In [41]:
arr.reshape((5,5))

array([[0.68910005, 0.98061642, 0.8044563 , 0.19071096, 0.14393131],
       [0.06482917, 0.537428  , 0.87073117, 0.84501176, 0.81203825],
       [0.39533731, 0.14346841, 0.65920755, 0.98401088, 0.90914703],
       [0.10233533, 0.88033573, 0.37520208, 0.44566714, 0.18751585],
       [0.27021355, 0.48831245, 0.70425311, 0.01940983, 0.11725166]])

In [46]:
arr

array([[0.68910005, 0.98061642, 0.8044563 , 0.19071096, 0.14393131],
       [0.06482917, 0.537428  , 0.87073117, 0.84501176, 0.81203825],
       [0.39533731, 0.14346841, 0.65920755, 0.98401088, 0.90914703],
       [0.10233533, 0.88033573, 0.37520208, 0.44566714, 0.18751585],
       [0.27021355, 0.48831245, 0.70425311, 0.01940983, 0.11725166]])

> Exibindo a forma de arr

In [47]:
arr.shape

(5, 5)

> Exibindo o maior valor de arr

In [49]:
arr.max()

0.9840108768578899

> Exibindo o menor valor de arr

In [50]:
arr.min()

0.019409832084675727

> Exibindo a posição do maior valor de arr

In [52]:
arr.argmax()

13

> Exibindo a posição do menor valor de arr

In [53]:
arr.argmin()

23