# **Indexação e Fatiamento e arrays**

> Importando a Biblioteca NumPy

In [2]:
import numpy as np

> Usando arange para criar uma array que varia de 0 a 30 de 3 em 3.

In [3]:
arr = np.arange(0,30,3)

In [4]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

> Exibindo o índice 3 da arr

In [5]:
arr[3]

9

> Exibindo valores do índice 2 ao 5.

In [6]:
arr[2:5]

array([ 6,  9, 12])

> Exibindo valores até o índice 5

In [7]:
arr[:5]

array([ 0,  3,  6,  9, 12])

> Exibindo valores a partir do índice 2

In [8]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

> Atribuindo valor 100 para os índices a partir de 2

In [9]:
arr[2:] = 100

In [10]:
arr[2:] = 100

> Exibindo valores a partir do índice 2

In [11]:
arr[2:]

array([100, 100, 100, 100, 100, 100, 100, 100])

> Checando se os valores a partir do índice 2 é igual à 10, o que retornará uma array de valores bool

In [12]:
arr[2:] == 10

array([False, False, False, False, False, False, False, False])

> Atribuindo à arr uma array 5x10 com valores de 0 a 49

In [13]:
arr = np.arange(50).reshape((5,10))

In [14]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

> Exibindo as dimensões

In [15]:
arr.shape

(5, 10)

> Exibindo valores até a linha 3 em todas as colunas.

In [16]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [17]:
arr[:3][1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

> Atribuindo à arr2, arr até a linha 3 

In [18]:
arr2 = arr[:3]

In [19]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

> Igualando todos os valores de arr2 à 100

In [20]:
arr2[:] = 100

In [21]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

> Note que a atribuição serviu também na arr

In [22]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

> Atribuindo a arr2 uma cópia de arr em arr2

In [23]:
arr2 = arr[:].copy()

In [24]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

> Atribuindo uma array de 1 a 50 com tamanho 5x10 para arr

In [25]:
arr = np.arange(50).reshape((5,10))

> Exibindo os valores da linha 1 a 4, a partir da quinta coluna

In [26]:
arr[1:4,5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

> Checando os valores maiores que 50

In [27]:
arr > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

> Criando uma variavel de tipo booleano que será uma array de true e false satisfazendo a condição arr > 30 em todos os índices correspondentes

In [28]:
bo1 = arr > 30

In [29]:
bo1

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

> Mostrando os valores dos índices que satisfazem bo1

In [30]:
arr[bo1]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

> Atribuindo uma array que serão 30 valores de 0 a 100 igualmente espaçados

In [31]:
array = np.linspace(0,100,30)

> Atribuindo a forma 2x15

In [32]:
array = array.reshape(2,15)

In [33]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
         41.37931034,  44.82758621,  48.27586207],
       [ 51.72413793,  55.17241379,  58.62068966,  62.06896552,
         65.51724138,  68.96551724,  72.4137931 ,  75.86206897,
         79.31034483,  82.75862069,  86.20689655,  89.65517241,
         93.10344828,  96.55172414, 100.        ]])

In [34]:
array[0:2,2] 

array([ 6.89655172, 58.62068966])